use crate::input::keys::VKey;
use crate::input::normalize::KeyState;
use windows::Win32::UI::Input::KeyboardAndMouse::{
    MapVirtualKeyW, SendInput, INPUT, INPUT_0, INPUT_KEYBOARD, KEYBDINPUT, KEYBD_EVENT_FLAGS,
    KEYEVENTF_EXTENDEDKEY, KEYEVENTF_KEYUP, MAPVK_VK_TO_VSC, VIRTUAL_KEY,
};

/// Magic tag attached to dwExtraInfo for all synthesized events generated by this application.
/// Used by the input pipeline to immediately detect and bypass self-injected input, preventing recursive storms.
pub const KCC_MAGIC_EXTRA_INFO: usize = 0x4B434331; // ASCII "KCC1"

pub struct InputInjector;

impl InputInjector {
    /// Synthesizes a keypress event into the Windows OS input queue tagged with our magic extra info.
    /// Accurately populates virtual key, hardware scan code, and extended key flags for 100% OS compatibility.
    pub fn inject_key(vkey: VKey, state: KeyState) {
        let raw_vk = vkey.to_vk();
        let scan_code = unsafe { MapVirtualKeyW(raw_vk as u32, MAPVK_VK_TO_VSC) as u16 };

        let mut flags = KEYBD_EVENT_FLAGS(0);
        if state == KeyState::Up {
            flags |= KEYEVENTF_KEYUP;
        }

        if Self::is_extended_key(vkey) {
            flags |= KEYEVENTF_EXTENDEDKEY;
        }

        let input = INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: VIRTUAL_KEY(raw_vk),
                    wScan: scan_code,
                    dwFlags: flags,
                    time: 0,
                    dwExtraInfo: KCC_MAGIC_EXTRA_INFO,
                },
            },
        };

        unsafe {
            let inputs = [input];
            let sent = SendInput(&inputs, std::mem::size_of::<INPUT>() as i32);
            if sent == 0 {
                tracing::warn!("SendInput returned 0 for injected key {:?}", vkey);
            }
        }
    }

    /// Determines if a virtual key requires the KEYEVENTF_EXTENDEDKEY flag on Windows.
    fn is_extended_key(vkey: VKey) -> bool {
        matches!(
            vkey,
            VKey::ArrowUp
                | VKey::ArrowDown
                | VKey::ArrowLeft
                | VKey::ArrowRight
                | VKey::Insert
                | VKey::Delete
                | VKey::Home
                | VKey::End
                | VKey::PageUp
                | VKey::PageDown
                | VKey::ControlRight
                | VKey::AltRight
                | VKey::WinLeft
                | VKey::WinRight
                | VKey::PrintScreen
                | VKey::VolumeMute
                | VKey::VolumeDown
                | VKey::VolumeUp
                | VKey::MediaNext
                | VKey::MediaPrev
                | VKey::MediaStop
                | VKey::MediaPlayPause
        )
    }
}
