use crate::input::keys::VKey;
use crate::input::normalize::KeyState;
use windows::Win32::UI::Input::KeyboardAndMouse::{
    SendInput, INPUT, INPUT_0, INPUT_KEYBOARD, KEYBDINPUT, KEYBD_EVENT_FLAGS, KEYEVENTF_KEYUP,
    VIRTUAL_KEY,
};

/// Magic tag attached to dwExtraInfo for all synthesized events generated by this application.
/// Used by the input pipeline to immediately detect and bypass self-injected input, preventing recursive storms.
pub const KCC_MAGIC_EXTRA_INFO: usize = 0x4B434331; // ASCII "KCC1"

pub struct InputInjector;

impl InputInjector {
    /// Synthesizes a keypress event into the Windows OS input queue tagged with our magic extra info.
    pub fn inject_key(vkey: VKey, state: KeyState) {
        let raw_vk = vkey.to_vk();
        let mut flags = KEYBD_EVENT_FLAGS(0);
        if state == KeyState::Up {
            flags |= KEYEVENTF_KEYUP;
        }

        let input = INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT {
                    wVk: VIRTUAL_KEY(raw_vk),
                    wScan: 0,
                    dwFlags: flags,
                    time: 0,
                    dwExtraInfo: KCC_MAGIC_EXTRA_INFO,
                },
            },
        };

        unsafe {
            let inputs = [input];
            SendInput(&inputs, std::mem::size_of::<INPUT>() as i32);
        }
    }
}
