use serde::{Deserialize, Serialize};

/// Strongly-typed Windows Virtual Key codes supported by the Keyboard Control Center.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[repr(u16)]
pub enum VKey {
    // Alphanumeric
    KeyA = 0x41,
    KeyB = 0x42,
    KeyC = 0x43,
    KeyD = 0x44,
    KeyE = 0x45,
    KeyF = 0x46,
    KeyG = 0x47,
    KeyH = 0x48,
    KeyI = 0x49,
    KeyJ = 0x4A,
    KeyK = 0x4B,
    KeyL = 0x4C,
    KeyM = 0x4D,
    KeyN = 0x4E,
    KeyO = 0x4F,
    KeyP = 0x50,
    KeyQ = 0x51,
    KeyR = 0x52,
    KeyS = 0x53,
    KeyT = 0x54,
    KeyU = 0x55,
    KeyV = 0x56,
    KeyW = 0x57,
    KeyX = 0x58,
    KeyY = 0x59,
    KeyZ = 0x5A,

    // Top Row Numbers
    Num0 = 0x30,
    Num1 = 0x31,
    Num2 = 0x32,
    Num3 = 0x33,
    Num4 = 0x34,
    Num5 = 0x35,
    Num6 = 0x36,
    Num7 = 0x37,
    Num8 = 0x38,
    Num9 = 0x39,

    // Function Keys
    F1 = 0x70,
    F2 = 0x71,
    F3 = 0x72,
    F4 = 0x73,
    F5 = 0x74,
    F6 = 0x75,
    F7 = 0x76,
    F8 = 0x77,
    F9 = 0x78,
    F10 = 0x79,
    F11 = 0x7A,
    F12 = 0x7B,

    // Modifiers
    ShiftLeft = 0xA0,
    ShiftRight = 0xA1,
    ControlLeft = 0xA2,
    ControlRight = 0xA3,
    AltLeft = 0xA4,
    AltRight = 0xA5,
    WinLeft = 0x5B,
    WinRight = 0x5C,

    // Common Control / Navigation
    Escape = 0x1B,
    Space = 0x20,
    Enter = 0x0D,
    Backspace = 0x08,
    Tab = 0x09,
    CapsLock = 0x14,
    Delete = 0x2E,
    Insert = 0x2D,
    Home = 0x24,
    End = 0x23,
    PageUp = 0x21,
    PageDown = 0x22,

    // Arrow Keys
    ArrowUp = 0x26,
    ArrowDown = 0x28,
    ArrowLeft = 0x25,
    ArrowRight = 0x27,

    // Symbols & Punctuation
    Backquote = 0xC0,      // ` ~
    Minus = 0xBD,          // - _
    Equal = 0xBB,          // = +
    BracketLeft = 0xDB,    // [ {
    BracketRight = 0xDD,   // ] }
    Backslash = 0xDC,      // \ |
    Semicolon = 0xBA,      // ; :
    Quote = 0xDE,          // ' "
    Comma = 0xBC,          // , <
    Period = 0xBE,         // . >
    Slash = 0xBF,          // / ?

    // Media & System Keys
    PrintScreen = 0x2C,
    ScrollLock = 0x91,
    Pause = 0x13,
    VolumeMute = 0xAD,
    VolumeDown = 0xAE,
    VolumeUp = 0xAF,
    MediaNext = 0xB0,
    MediaPrev = 0xB1,
    MediaStop = 0xB2,
    MediaPlayPause = 0xB3,

    // Other / Unknown
    Unknown(u16),
}

impl VKey {
    /// Convert from a Win32 virtual-key code (VK_*).
    pub fn from_vk(code: u16) -> Self {
        match code {
            0x41 => VKey::KeyA,
            0x42 => VKey::KeyB,
            0x43 => VKey::KeyC,
            0x44 => VKey::KeyD,
            0x45 => VKey::KeyE,
            0x46 => VKey::KeyF,
            0x47 => VKey::KeyG,
            0x48 => VKey::KeyH,
            0x49 => VKey::KeyI,
            0x4A => VKey::KeyJ,
            0x4B => VKey::KeyK,
            0x4C => VKey::KeyL,
            0x4D => VKey::KeyM,
            0x4E => VKey::KeyN,
            0x4F => VKey::KeyO,
            0x50 => VKey::KeyP,
            0x51 => VKey::KeyQ,
            0x52 => VKey::KeyR,
            0x53 => VKey::KeyS,
            0x54 => VKey::KeyT,
            0x55 => VKey::KeyU,
            0x56 => VKey::KeyV,
            0x57 => VKey::KeyW,
            0x58 => VKey::KeyX,
            0x59 => VKey::KeyY,
            0x5A => VKey::KeyZ,

            0x30 => VKey::Num0,
            0x31 => VKey::Num1,
            0x32 => VKey::Num2,
            0x33 => VKey::Num3,
            0x34 => VKey::Num4,
            0x35 => VKey::Num5,
            0x36 => VKey::Num6,
            0x37 => VKey::Num7,
            0x38 => VKey::Num8,
            0x39 => VKey::Num9,

            0x70 => VKey::F1,
            0x71 => VKey::F2,
            0x72 => VKey::F3,
            0x73 => VKey::F4,
            0x74 => VKey::F5,
            0x75 => VKey::F6,
            0x76 => VKey::F7,
            0x77 => VKey::F8,
            0x78 => VKey::F9,
            0x79 => VKey::F10,
            0x7A => VKey::F11,
            0x7B => VKey::F12,

            0xA0 | 0x10 => VKey::ShiftLeft,
            0xA1 => VKey::ShiftRight,
            0xA2 | 0x11 => VKey::ControlLeft,
            0xA3 => VKey::ControlRight,
            0xA4 | 0x12 => VKey::AltLeft,
            0xA5 => VKey::AltRight,
            0x5B => VKey::WinLeft,
            0x5C => VKey::WinRight,

            0x1B => VKey::Escape,
            0x20 => VKey::Space,
            0x0D => VKey::Enter,
            0x08 => VKey::Backspace,
            0x09 => VKey::Tab,
            0x14 => VKey::CapsLock,
            0x2E => VKey::Delete,
            0x2D => VKey::Insert,
            0x24 => VKey::Home,
            0x23 => VKey::End,
            0x21 => VKey::PageUp,
            0x22 => VKey::PageDown,

            0x26 => VKey::ArrowUp,
            0x28 => VKey::ArrowDown,
            0x25 => VKey::ArrowLeft,
            0x27 => VKey::ArrowRight,

            0xC0 => VKey::Backquote,
            0xBD => VKey::Minus,
            0xBB => VKey::Equal,
            0xDB => VKey::BracketLeft,
            0xDD => VKey::BracketRight,
            0xDC => VKey::Backslash,
            0xBA => VKey::Semicolon,
            0xDE => VKey::Quote,
            0xBC => VKey::Comma,
            0xBE => VKey::Period,
            0xBF => VKey::Slash,

            0x2C => VKey::PrintScreen,
            0x91 => VKey::ScrollLock,
            0x13 => VKey::Pause,
            0xAD => VKey::VolumeMute,
            0xAE => VKey::VolumeDown,
            0xAF => VKey::VolumeUp,
            0xB0 => VKey::MediaNext,
            0xB1 => VKey::MediaPrev,
            0xB2 => VKey::MediaStop,
            0xB3 => VKey::MediaPlayPause,

            other => VKey::Unknown(other),
        }
    }

    /// Return the raw Windows Virtual Key code.
    pub fn to_vk(&self) -> u16 {
        match self {
            VKey::Unknown(code) => *code,
            // For known variants, cast repr(u16)
            VKey::KeyA => 0x41,
            VKey::KeyB => 0x42,
            VKey::KeyC => 0x43,
            VKey::KeyD => 0x44,
            VKey::KeyE => 0x45,
            VKey::KeyF => 0x46,
            VKey::KeyG => 0x47,
            VKey::KeyH => 0x48,
            VKey::KeyI => 0x49,
            VKey::KeyJ => 0x4A,
            VKey::KeyK => 0x4B,
            VKey::KeyL => 0x4C,
            VKey::KeyM => 0x4D,
            VKey::KeyN => 0x4E,
            VKey::KeyO => 0x4F,
            VKey::KeyP => 0x50,
            VKey::KeyQ => 0x51,
            VKey::KeyR => 0x52,
            VKey::KeyS => 0x53,
            VKey::KeyT => 0x54,
            VKey::KeyU => 0x55,
            VKey::KeyV => 0x56,
            VKey::KeyW => 0x57,
            VKey::KeyX => 0x58,
            VKey::KeyY => 0x59,
            VKey::KeyZ => 0x5A,

            VKey::Num0 => 0x30,
            VKey::Num1 => 0x31,
            VKey::Num2 => 0x32,
            VKey::Num3 => 0x33,
            VKey::Num4 => 0x34,
            VKey::Num5 => 0x35,
            VKey::Num6 => 0x36,
            VKey::Num7 => 0x37,
            VKey::Num8 => 0x38,
            VKey::Num9 => 0x39,

            VKey::F1 => 0x70,
            VKey::F2 => 0x71,
            VKey::F3 => 0x72,
            VKey::F4 => 0x73,
            VKey::F5 => 0x74,
            VKey::F6 => 0x75,
            VKey::F7 => 0x76,
            VKey::F8 => 0x77,
            VKey::F9 => 0x78,
            VKey::F10 => 0x79,
            VKey::F11 => 0x7A,
            VKey::F12 => 0x7B,

            VKey::ShiftLeft => 0xA0,
            VKey::ShiftRight => 0xA1,
            VKey::ControlLeft => 0xA2,
            VKey::ControlRight => 0xA3,
            VKey::AltLeft => 0xA4,
            VKey::AltRight => 0xA5,
            VKey::WinLeft => 0x5B,
            VKey::WinRight => 0x5C,

            VKey::Escape => 0x1B,
            VKey::Space => 0x20,
            VKey::Enter => 0x0D,
            VKey::Backspace => 0x08,
            VKey::Tab => 0x09,
            VKey::CapsLock => 0x14,
            VKey::Delete => 0x2E,
            VKey::Insert => 0x2D,
            VKey::Home => 0x24,
            VKey::End => 0x23,
            VKey::PageUp => 0x21,
            VKey::PageDown => 0x22,

            VKey::ArrowUp => 0x26,
            VKey::ArrowDown => 0x28,
            VKey::ArrowLeft => 0x25,
            VKey::ArrowRight => 0x27,

            VKey::Backquote => 0xC0,
            VKey::Minus => 0xBD,
            VKey::Equal => 0xBB,
            VKey::BracketLeft => 0xDB,
            VKey::BracketRight => 0xDD,
            VKey::Backslash => 0xDC,
            VKey::Semicolon => 0xBA,
            VKey::Quote => 0xDE,
            VKey::Comma => 0xBC,
            VKey::Period => 0xBE,
            VKey::Slash => 0xBF,

            VKey::PrintScreen => 0x2C,
            VKey::ScrollLock => 0x91,
            VKey::Pause => 0x13,
            VKey::VolumeMute => 0xAD,
            VKey::VolumeDown => 0xAE,
            VKey::VolumeUp => 0xAF,
            VKey::MediaNext => 0xB0,
            VKey::MediaPrev => 0xB1,
            VKey::MediaStop => 0xB2,
            VKey::MediaPlayPause => 0xB3,
        }
    }

    /// User-friendly label for UI keycaps and displays.
    pub fn label(&self) -> &'static str {
        match self {
            VKey::KeyA => "A",
            VKey::KeyB => "B",
            VKey::KeyC => "C",
            VKey::KeyD => "D",
            VKey::KeyE => "E",
            VKey::KeyF => "F",
            VKey::KeyG => "G",
            VKey::KeyH => "H",
            VKey::KeyI => "I",
            VKey::KeyJ => "J",
            VKey::KeyK => "K",
            VKey::KeyL => "L",
            VKey::KeyM => "M",
            VKey::KeyN => "N",
            VKey::KeyO => "O",
            VKey::KeyP => "P",
            VKey::KeyQ => "Q",
            VKey::KeyR => "R",
            VKey::KeyS => "S",
            VKey::KeyT => "T",
            VKey::KeyU => "U",
            VKey::KeyV => "V",
            VKey::KeyW => "W",
            VKey::KeyX => "X",
            VKey::KeyY => "Y",
            VKey::KeyZ => "Z",

            VKey::Num0 => "0",
            VKey::Num1 => "1",
            VKey::Num2 => "2",
            VKey::Num3 => "3",
            VKey::Num4 => "4",
            VKey::Num5 => "5",
            VKey::Num6 => "6",
            VKey::Num7 => "7",
            VKey::Num8 => "8",
            VKey::Num9 => "9",

            VKey::F1 => "F1",
            VKey::F2 => "F2",
            VKey::F3 => "F3",
            VKey::F4 => "F4",
            VKey::F5 => "F5",
            VKey::F6 => "F6",
            VKey::F7 => "F7",
            VKey::F8 => "F8",
            VKey::F9 => "F9",
            VKey::F10 => "F10",
            VKey::F11 => "F11",
            VKey::F12 => "F12",

            VKey::ShiftLeft => "Shift",
            VKey::ShiftRight => "Shift",
            VKey::ControlLeft => "Ctrl",
            VKey::ControlRight => "Ctrl",
            VKey::AltLeft => "Alt",
            VKey::AltRight => "Alt",
            VKey::WinLeft => "Win",
            VKey::WinRight => "Win",

            VKey::Escape => "Esc",
            VKey::Space => "Space",
            VKey::Enter => "Enter",
            VKey::Backspace => "Bksp",
            VKey::Tab => "Tab",
            VKey::CapsLock => "Caps",
            VKey::Delete => "Del",
            VKey::Insert => "Ins",
            VKey::Home => "Home",
            VKey::End => "End",
            VKey::PageUp => "PgUp",
            VKey::PageDown => "PgDn",

            VKey::ArrowUp => "▲",
            VKey::ArrowDown => "▼",
            VKey::ArrowLeft => "◀",
            VKey::ArrowRight => "▶",

            VKey::Backquote => "`",
            VKey::Minus => "-",
            VKey::Equal => "=",
            VKey::BracketLeft => "[",
            VKey::BracketRight => "]",
            VKey::Backslash => "\\",
            VKey::Semicolon => ";",
            VKey::Quote => "'",
            VKey::Comma => ",",
            VKey::Period => ".",
            VKey::Slash => "/",

            VKey::PrintScreen => "PrtSc",
            VKey::ScrollLock => "ScrLk",
            VKey::Pause => "Pause",
            VKey::VolumeMute => "Mute",
            VKey::VolumeDown => "Vol-",
            VKey::VolumeUp => "Vol+",
            VKey::MediaNext => "Next",
            VKey::MediaPrev => "Prev",
            VKey::MediaStop => "Stop",
            VKey::MediaPlayPause => "Play",

            VKey::Unknown(_) => "???",
        }
    }
}
